import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import BgPannel from "./_components/BgPannel";
import Header from "./_components/Header";
import { SolanaProvider } from "./_components/web3/SolanaProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`p-3 md:p-5 ${geistSans.variable} ${notoSans.variable} ${geistMono.variable} antialiased`}
      >
        <SolanaProvider

        >
          <Header />
          <BgPannel>
            {children}
          </BgPannel>
        </SolanaProvider>
      </body>
    </html>
  );
}
